---
- name: restart openvswitch
  systemd:
    name: openvswitch
    state: restarted
  when: (not skip_node_svc_handlers | default(False) | bool) and not (ovs_service_status_changed | default(false) | bool) and openshift.common.use_openshift_sdn | bool
  register: l_openshift_node_stop_openvswitch_result
  until: not l_openshift_node_stop_openvswitch_result | failed
  retries: 3
  delay: 30
  notify:
  - kamesh restart NetworkManager
  - restart openvswitch pause

# i dont know why resolv.conf not getting triggered hence triggering this call forcibly
- name: kamesh restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted

- name: restart openvswitch pause
  pause: seconds=15
  when: (not skip_node_svc_handlers | default(False) | bool) and openshift.common.is_containerized | bool

- name: restart node
  systemd:
    name: "{{ openshift.common.service_type }}-node"
    state: restarted
  register: l_openshift_node_restart_node_result
  until: not l_openshift_node_restart_node_result | failed
  retries: 3
  delay: 30
  when:
  - (not skip_node_svc_handlers | default(False) | bool)
  - not (node_service_status_changed | default(false) | bool)

- name: reload sysctl.conf
  command: /sbin/sysctl -p

- name: reload systemd units
  command: systemctl daemon-reload
